<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTYNNYMS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTYNNYMS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTYNNYMS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTYNNYMS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTYNNYMS\App_KernelDevDebugContainer([
    'container.build_hash' => 'TYNNYMS',
    'container.build_id' => '89758ba3',
    'container.build_time' => 1633275369,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTYNNYMS');
