<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'index' => [[], ['_controller' => 'App\\Controller\\ContactListController::index'], [], [['text', '/']], [], []],
    'create' => [[], ['_controller' => 'App\\Controller\\ContactListController::create'], [], [['text', '/create']], [], []],
    'update' => [['id'], ['_controller' => 'App\\Controller\\ContactListController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/update']], [], []],
    'delete' => [['id'], ['_controller' => 'App\\Controller\\ContactListController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/delete']], [], []],
    'email_check' => [['input_val'], ['_controller' => 'App\\Controller\\ContactListController::emailCheck'], [], [['variable', '/', '[^/]++', 'input_val', true], ['text', '/email_check']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
